version: '3'
services:
  redis-server:
    image: 'redis'
  python-app:
#    restart: always
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
     - "8080:5000"
    volumes:
     - .:/app
  tests:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - .:/app
    command: ["python3", "test_sample.py"]